source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               lib/javaparser-core-3.28.0.jar,\
               lib/javaparser-symbol-solver-core-3.28.0.jar
